# Generated by Django 4.2.13 on 2024-10-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_remove_user_country_delete_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='аватар'),
        ),
    ]
